# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [1]:
# import libraries
import pandas as pd
import numpy as np

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [2]:
# import dataset
pokemon = pd.read_csv('pokemon.csv')

#### Print first 10 rows of `pokemon`.

In [3]:
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

In [4]:
pokemon=pokemon.rename(columns={'#':'ID'})
pokemon.head(10)

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [5]:
Type1 = pokemon['Type 1'].unique()
Type2 = pokemon['Type 2'].unique()
Types = pd.DataFrame(list(zip(Type1, Type2)), columns = ['Type1','Type2'])
Types

       Type1     Type2
0      Grass    Poison
1       Fire       NaN
2      Water    Flying
3        Bug    Dragon
4     Normal    Ground
5     Poison     Fairy
6   Electric     Grass
7     Ground  Fighting
8      Fairy   Psychic
9   Fighting     Steel
10   Psychic       Ice
11      Rock      Rock
12     Ghost      Dark
13       Ice     Water
14    Dragon  Electric
15      Dark      Fire
16     Steel     Ghost
17    Flying       Bug

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [6]:
pokemon['Name'].unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoran♀', 'Nidorina', 'Nidoqueen', 'Nidoran♂',
       'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix',
       'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
       'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat',
       'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
       'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine',
       'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam',
       'AlakazamMega Alakazam', 'Machop', 'Machoke', 'Machamp',
       'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Magnemite',
       'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong',
       'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
       'Gengar', 'GengarMega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Horsea',
       'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir',
       'PinsirMega Pinsir', 'Tauros', 'Magikarp', 'Gyarados',
       'GyaradosMega Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon',
       'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto',
       'Kabutops', 'Aerodactyl', 'AerodactylMega Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'MewtwoMega Mewtwo X',
       'MewtwoMega Mewtwo Y', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'AmpharosMega Ampharos',
       'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
       'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
       'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
       'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
       'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix',
       'SteelixMega Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
       'Scizor', 'ScizorMega Scizor', 'Shuckle', 'Heracross',
       'HeracrossMega Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'HoundoomMega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'TyranitarMega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'SceptileMega Sceptile', 'Torchic',
       'Combusken', 'Blaziken', 'BlazikenMega Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'SwampertMega Swampert', 'Poochyena',
       'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon',
       'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull',
       'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'GardevoirMega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
       'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
       'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita',
       'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye',
       'SableyeMega Sableye', 'Mawile', 'MawileMega Mawile', 'Aron',
       'Lairon', 'Aggron', 'AggronMega Aggron', 'Meditite', 'Medicham',
       'MedichamMega Medicham', 'Electrike', 'Manectric',
       'ManectricMega Manectric', 'Plusle', 'Minun', 'Volbeat',
       'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'SharpedoMega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'CameruptMega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'AltariaMega Altaria', 'Zangoose', 'Seviper',
       'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
       'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
       'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
       'Banette', 'BanetteMega Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'AbsolMega Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'GlalieMega Glalie', 'Spheal', 'Sealeo', 'Walrein',
       'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
       'Shelgon', 'Salamence', 'SalamenceMega Salamence', 'Beldum',
       'Metang', 'Metagross', 'MetagrossMega Metagross', 'Regirock',
       'Regice', 'Registeel', 'Latias', 'LatiasMega Latias', 'Latios',
       'LatiosMega Latios', 'Kyogre', 'KyogrePrimal Kyogre', 'Groudon',
       'GroudonPrimal Groudon', 'Rayquaza', 'RayquazaMega Rayquaza',
       'Jirachi', 'DeoxysNormal Forme', 'DeoxysAttack Forme',
       'DeoxysDefense Forme', 'DeoxysSpeed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'WormadamPlant Cloak', 'WormadamSandy Cloak',
       'WormadamTrash Cloak', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'LopunnyMega Lopunny', 'Mismagius', 'Honchkrow',
       'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb',
       'Gible', 'Gabite', 'Garchomp', 'GarchompMega Garchomp', 'Munchlax',
       'Riolu', 'Lucario', 'LucarioMega Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'AbomasnowMega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'GalladeMega Gallade',
       'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'RotomHeat Rotom',
       'RotomWash Rotom', 'RotomFrost Rotom', 'RotomFan Rotom',
       'RotomMow Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia',
       'Heatran', 'Regigigas', 'GiratinaAltered Forme',
       'GiratinaOrigin Forme', 'Cresselia', 'Phione', 'Manaphy',
       'Darkrai', 'ShayminLand Forme', 'ShayminSky Forme', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
       'AudinoMega Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole',
       'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon',
       'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
       'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile',
       'Krokorok', 'Krookodile', 'Darumaka', 'DarmanitanStandard Mode',
       'DarmanitanZen Mode', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy',
       'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
       'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor',
       'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita',
       'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett',
       'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
       'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus',
       'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik',
       'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'TornadusIncarnate Forme',
       'TornadusTherian Forme', 'ThundurusIncarnate Forme',
       'ThundurusTherian Forme', 'Reshiram', 'Zekrom',
       'LandorusIncarnate Forme', 'LandorusTherian Forme', 'Kyurem',
       'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'KeldeoOrdinary Forme',
       'KeldeoResolute Forme', 'MeloettaAria Forme',
       'MeloettaPirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'Flabébé', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'MeowsticMale', 'MeowsticFemale', 'Honedge', 'Doublade',
       'AegislashBlade Forme', 'AegislashShield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'PumpkabooAverage Size', 'PumpkabooSmall Size',
       'PumpkabooLarge Size', 'PumpkabooSuper Size',
       'GourgeistAverage Size', 'GourgeistSmall Size',
       'GourgeistLarge Size', 'GourgeistSuper Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde50% Forme', 'Diancie', 'DiancieMega Diancie',
       'HoopaHoopa Confined', 'HoopaHoopa Unbound', 'Volcanion'],
      dtype=object)

In [7]:
# your code here

def rename_mega(txt):
    if 'Mega' in txt:
        second_part = txt.split("Mega")[-1]
        return 'Mega' + second_part
    else:
        return txt
    

pokemon['Name']=pokemon['Name'].apply(lambda x: rename_mega(x))

# test transformed data
pokemon.head(10)

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [8]:
# your code here
pokemon['A/D Ratio'] = pokemon['Attack'] / pokemon['Defense']
pokemon.head(10)

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462

#### Identify the pokemon with the highest `A/D Ratio`.

In [9]:
# your code here
pokemon[pokemon['A/D Ratio']==pokemon['A/D Ratio'].max()]

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

#### Identify the pokemon with the lowest A/D Ratio.

In [10]:
# your code here
pokemon[pokemon['A/D Ratio']==pokemon['A/D Ratio'].min()]

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [11]:
# your code here

def combo_type(type1, type2):
        if str(type2) == 'nan':
            return type1
        else:
            return str(type1) + "_" + str(type2)
    

pokemon['Combo Type']=pokemon.apply(lambda x: combo_type(x['Type 1'],x['Type 2']), axis=1)

pokemon.head(10)

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass_Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass_Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass_Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass_Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448,Fire
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923,Fire_Flying
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171,Fire_Dragon
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333,Fire_Flying
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462,Water

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [12]:
# your code here

display(pokemon.sort_values(by=['A/D Ratio']).tail(5)) #finding the 5 highest ratios
top_5_ratio = pokemon[pokemon["A/D Ratio"]>=3] # listing all pokemon which have those ratios
top_5_ratio

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True,3.000,Psychic
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug_Poison
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water_Dark
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug_Poison
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water_Dark
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water_Dark
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True,3.000,Psychic
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False,3.000,Steel_Ghost

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [13]:
# your code here

top_types = top_5_ratio['Combo Type'].unique()
print(top_types)

['Bug_Poison' 'Water_Dark' 'Psychic' 'Rock' 'Steel_Ghost']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [14]:
pokemon_top = pokemon[pokemon['Combo Type'].isin(top_types)]
pokemon_top.head(10)

,ID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,1.166667,Bug_Poison
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,0.500000,Bug_Poison
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,2.250000,Bug_Poison
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000,Bug_Poison
53,48,Venonat,Bug,Poison,305,60,55,50,40,55,45,1,False,1.100000,Bug_Poison
54,49,Venomoth,Bug,Poison,450,70,65,60,90,75,90,1,False,1.083333,Bug_Poison
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False,1.333333,Psychic
69,64,Kadabra,Psychic,NaN,400,40,35,30,120,70,105,1,False,1.166667,Psychic
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False,1.111111,Psychic
71,65,Mega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False,0.769231,Psychic

In [15]:
# your code here

mean_pokemon = pokemon_top.pivot_table( index= ['Combo Type'], aggfunc = ['mean'])
mean_pokemon

                 mean                                                \
            A/D Ratio      Attack     Defense Generation         HP
Combo Type
Bug_Poison   1.315989   68.333333   58.083333   2.333333  53.750000
Psychic      1.164196   64.947368   67.236842   3.342105  72.552632
Rock         1.260091  103.333333  107.222222   3.888889  67.111111
Steel_Ghost  1.216667   97.500000  112.500000   6.000000  56.000000
Water_Dark   2.291949  120.000000   65.166667   3.166667  69.166667


                     ID Legendary    Sp. Atk    Sp. Def      Speed       Total
Combo Type
Bug_Poison   199.166667  0.000000  42.500000  59.333333  65.916667  347.916667
Psychic      381.973684  0.236842  98.552632  82.394737  78.868421  464.552632
Rock         410.111111  0.111111  40.555556  58.333333  32.888889  409.444444
Steel_Ghost  680.250000  0.000000  70.000000  71.500000  45.750000  453.250000
Water_Dark   347.666667  0.000000  88.833333  63.500000  87.166667  493.833333